name: Resume-CI

on: [push]

jobs:
  build-job:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: kuroyi/awesome-cv-action@0.0.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        FILE_NAME: 'rick-haines.tex'
